### ISSUE TITLE
protocol36359 is actually 36144

### ISSUE THREAD

**Issue by regner** [jnovack/heroes-replays#1]
You can see it right in your json output:  https://github.com/jnovack/heroes-replays/blob/master/json/protocol36359/header.json

:)

**Comment by regner** [comment]
I guess more specifically the m_build and m_baseBuild are different for that one. Which isn't the case for any of the others.

**Comment by jnovack** [comment]
Yes, you found the issue.  `m_build` is the field you should be querying on for the build, NOT `baseBuild`.

**Comment by jnovack** [comment]
During my testing, there are a number of protocols which are exactly the same, no changes were made to the replay file.

However, the StormReplay files are written by the "build" of the application, not by the "baseBuild".  In this instance, 36359 is EXACTLY the same as 36144, and thus you could parse the 36359 replay file with 36144.  However, 36359 refers to the build of the application which wrote the file, even though it was using 36144's protocol.

There was a protocol for it, so I uploaded a replay for it.  I consider it an upstream issue (or more specifically, a non-issue) since they released protocols based on builds.

**Comment by jnovack** [comment]
But, excellent find, I commend this level of scrutiny, and the reason I uploaded I the files. :)

![](http://cdn.theatlantic.com/assets/media/img/mt/2014/09/The_More_You_Know/lead_large.png)
